# Generated by Django 2.2.1 on 2019-05-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190510_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quauntity',
            new_name='quantity',
        ),
    ]
