# Generated by Django 2.2.1 on 2019-06-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0003_auto_20190613_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='commute/%Y/%m/'),
        ),
    ]
