# Generated by Django 2.1.7 on 2019-04-09 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190409_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_user',
        ),
        migrations.AddField(
            model_name='post',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_user_set', through='blog.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
