# Generated by Django 2.1.7 on 2019-04-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190409_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_user_set',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
