# Generated by Django 2.2.1 on 2019-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190514_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
