# Generated by Django 2.2.1 on 2019-05-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hit',
        ),
    ]
